// Generated by CoffeeScript 1.7.1
var Html2Text, JQuery, JSDom, http, mod, randQuote;

JSDom = require('jsdom');

JQuery = require('jquery');

Html2Text = require('html-to-text');

http = require('http');

JQuery.fromURL = function(url, cb) {
  return JSDom.env({
    url: url,
    done: function(error, window) {
      var $;
      $ = JQuery(window);
      return cb($, window, error);
    }
  });
};

mod = randQuote = function(cb) {
  return mod.randURL(function(url, res, err) {
    return mod.quoteFrom(url, cb);
  });
};

mod.randQuote = randQuote;

mod.randURL = function(cb) {
  var con, opt;
  opt = {
    host: 'discordianquotes.com',
    path: '/random',
    method: 'HEAD'
  };
  con = http.request(opt, function(res) {
    return cb(res.headers.location, res);
  });
  return con.end();
};

mod.quoteFrom = function(url, cb) {
  return JQuery.fromURL(url, function($, win, err) {
    var txt;
    txt = Html2Text.fromString($(".quote").html());
    return cb(txt, {
      url: url
    });
  });
};

module.exports = mod;
